// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _3d_pasatiempos_backend.Infrastructure.Persistence.DataContext;

#nullable disable

namespace _3d_pasatiempos_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("customer_pkey");

                    b.HasIndex(new[] { "Name" }, "idx_customer_name");

                    b.ToTable("customer", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("expense_pkey");

                    b.HasIndex(new[] { "OrderId" }, "idx_expense_order_id");

                    b.ToTable("expense", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerGram")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_gram");

                    b.HasKey("Id")
                        .HasName("material_pkey");

                    b.ToTable("material", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer")
                        .HasColumnName("quote_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex(new[] { "QuoteId" }, "idx_orders_quote_id");

                    b.HasIndex(new[] { "QuoteId" }, "orders_quote_id_key")
                        .IsUnique();

                    b.ToTable("orders", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("payment_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("payment", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerMinute")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost_per_minute");

                    b.Property<decimal>("FailPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fail_percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("PowerConsumptionKwh")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("power_consumption_kwh");

                    b.Property<decimal>("PowerConsumptionWh")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("power_consumption_wh");

                    b.Property<int>("UsefulLifeHours")
                        .HasColumnType("integer")
                        .HasColumnName("useful_life_hours");

                    b.HasKey("Id")
                        .HasName("printer_pkey");

                    b.ToTable("printer", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EstimatedEndTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("estimated_end_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("GramsUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("grams_used");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TimeUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("time_used");

                    b.HasKey("Id")
                        .HasName("production_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("production", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("project_pkey");

                    b.HasIndex(new[] { "CustomerId" }, "idx_project_customer_id");

                    b.ToTable("project", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("quote_pkey");

                    b.HasIndex(new[] { "CustomerId" }, "idx_quote_customer_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_quote_project_id");

                    b.ToTable("quote", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.QuoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CalculatedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("calculated_price");

                    b.Property<decimal?>("CostOverrunFailure")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost_overrun_failure");

                    b.Property<decimal?>("CostPerKwhUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost_per_kwh_used");

                    b.Property<decimal?>("EstimatedGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_grams");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<decimal?>("MachineWearCostUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("machine_wear_cost_used");

                    b.Property<decimal?>("PricePerGramUsed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_gram_used");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("ProfitPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("profit_percentage");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer")
                        .HasColumnName("quote_id");

                    b.HasKey("Id")
                        .HasName("quote_item_pkey");

                    b.HasIndex(new[] { "QuoteId" }, "idx_quote_item_quote_id");

                    b.ToTable("quote_item", "app");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Expense", b =>
                {
                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Order", "Order")
                        .WithMany("Expense")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_expense_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Order", b =>
                {
                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Quote", "Quote")
                        .WithOne("Order")
                        .HasForeignKey("_3d_pasatiempos_backend.Domain.Entities.Order", "QuoteId")
                        .IsRequired()
                        .HasConstraintName("fk_orders_quote");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Order", "Order")
                        .WithMany("Payment")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_payment_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Production", b =>
                {
                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Order", "Order")
                        .WithMany("Production")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_production_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Project", b =>
                {
                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Customer", "Customer")
                        .WithMany("Project")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_project_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Quote", b =>
                {
                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Customer", "Customer")
                        .WithMany("Quote")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_quote_customer");

                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Project", "Project")
                        .WithMany("Quote")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_quote_project");

                    b.Navigation("Customer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.QuoteItem", b =>
                {
                    b.HasOne("_3d_pasatiempos_backend.Domain.Entities.Quote", "Quote")
                        .WithMany("QuoteItem")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_item_quote");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Project");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Order", b =>
                {
                    b.Navigation("Expense");

                    b.Navigation("Payment");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Project", b =>
                {
                    b.Navigation("Quote");
                });

            modelBuilder.Entity("_3d_pasatiempos_backend.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("QuoteItem");
                });
#pragma warning restore 612, 618
        }
    }
}
